### ISSUE TITLE
Playstore restrictions

### ISSUE THREAD

**Issue by bettkipronoh** [devfemibadmus/mediasaver#5]
I don't think playstore will approve the app because of the Storage permission, have you considered using SAF to access the status?

**Comment by devfemibadmus** [comment]
yes it was restricted, yes SAF access but i like smth else checkout this issue           https://github.com/flutter/flutter/issues/25659#issuecomment-1462496431 read till bottom then move to next one

**Comment by devfemibadmus** [comment]
**"As long as there are those who remember what was, there will always be those who cannot accept what can be."** so hard i tried again and explain to them the framework i uses and its limitation but for a Good security reason they dont allow which is Good thou, so i tried different method bcus i really wanna use @flutter and nothing else.........i tried below


- running localhost server (slowed when it comes to big data and users device matters)
- sending data in chunks(low performance)
- android view(work fine but take time for all to show once read [android view flutter performance](https://docs.flutter.dev/platform-integration/android/platform-views#performance)

Literally other option which flutter path provider did (copy files to place u can access) but i don't want that.........Yo man i am really tired i will try something else so it manage user storage

**Comment by devfemibadmus** [comment]
on playstore now
